# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0acf267086fc2e8eeefdb154d7d09f29"
name = "dev-store"
handle = "dev-store-19"
application_url = "https://strengthen-recreation-firefox-pale.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_themes,read_themes,write_products,read_products"

[auth]
redirect_urls = [
  "https://strengthen-recreation-firefox-pale.trycloudflare.com/auth/callback",
  "https://strengthen-recreation-firefox-pale.trycloudflare.com/auth/shopify/callback",
  "https://strengthen-recreation-firefox-pale.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
